name: Deploy Discord Commands
on:
  push:
    paths:
    - 'src/commands/**'
    branches:
      - main
jobs:
  deploy:
    name: Deploy Commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16'
      - run: yarn
      - run: yarn build
      - run: yarn deploy-commands
        env:
          CLIENT_ID: '${{ secrets.CLIENT_ID }}'
          TOKEN: '${{ secrets.TOKEN }}'
